name: marti_app
description: "A example app for marti"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.3
  provider: ^6.1.1
  location: ^5.0.3
  permission_handler: ^11.2.1
  flutter_background_geolocation: ^4.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true
