name: Pull Request

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Analyze project source
        run: flutter analyze
        
      - name: Format reminder
        run: |
          echo "⚠️ Not: Kodunuzun formatını kontrol etmek için 'dart format .' komutunu kullanabilirsiniz."
          echo "Format kontrolü pipeline'ı durdurmayacak, sadece bir hatırlatmadır."
        
      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
      - name: Format and check code
        run: |
          dart format .
          git add .
          if git diff --cached --quiet; then
            echo "No formatting changes needed"
          else
            echo "Code needs formatting. Please run 'dart format .' locally and commit the changes."
            git diff --cached
            exit 1
          fi 