name: Pull Request

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Analyze project source
        run: flutter analyze
        
      - name: Format code
        run: dart format .
        
      - name: Check if any files were formatted
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code formatting is incorrect. Please run 'dart format .' locally and commit the changes."
            git diff
            exit 1
          fi 